language: node_js

node_js:
  - "11"
  
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  - npm run build-prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: #git_token
  local_dir: build
  on:
    branch: master
