language: node_js

node_js:
  - "11"
  
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  - npm run build-prod

deploy:
  provider: surge
  skip_cleanup: true
  domain: ashishpatel.surge.sh
  project: ./build/
  on:
    branch: master
